[package]
name = "d2r-item-keeper"
version = "0.1.0"
description = "D2R item keep/chuck desktop overlay"
authors = ["brian-cook"]
license = "MIT"
repository = "https://github.com/brian-cook/d2r-item-keeper"
edition = "2021"
rust-version = "1.77"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
